config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants do
    resources :reviews, only: %i[create]
  end
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = %w[chinese italian japanese french belgian]

  has_many :reviews, dependent: :destroy

  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @review = Review.new
  end

  def edit; end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'new'
    end
  end

  def destroy
    @restaurant.destroy

    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'restaurants/show', status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, class: "form-select", collection: Restaurant::CATEGORIES %>
  <%= f.submit(class: 'btn btn-success') %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>All restaurants</h1>
  <%= link_to("Create a restaurant", new_restaurant_path, class: 'btn btn-primary mb-3') %>

  <div class="d-flex gap-3">
    <% @restaurants.each do |restaurant| %>
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"><%= restaurant.name %></h5>
          <p class="card-text"><%= restaurant.category %></p>
          <%= link_to("Show more", restaurant_path(restaurant), class: 'btn btn-outline-dark btn-sm') %>
          <%= link_to("Delete", restaurant_path(restaurant), class: 'btn btn-danger btn-sm', data: {turbo_method: :delete, turbo_confirm: "Are you sure to delete this resto ?"}) %>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/restaurants/new.html.erb
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/show.html.erb
.<div class="container-fluid ">
  <h1>Name : <%= @restaurant.name %></h1>
  <p>Address : <%= @restaurant.address %></p>
  <p>Phone Number : <%= @restaurant.phone_number %></p>
  <p>Category : <%= @restaurant.category %></p>

  <%= link_to "Edit", edit_restaurant_path(@restaurant), class: 'btn btn-primary' %>
  <%= link_to "List of restaurants", restaurants_path, class: 'btn btn-warning' %>


  <h2 class = "mt-5">Reviews</h2>
    <% @restaurant.reviews.each do |review| %>
      <div class="shadow-sm p-3 mb-3 bg-body rounded w-50">
      Content : <%= review.content %> 
      Rating : <%= review.rating %> 
      <%= link_to("Delete", review_path(review), class: 'btn btn-danger btn-sm', data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}) %>
      </div>
    <% end %>

  <%= render "reviews/form", restaurant: @restaurant, review: @review %> 
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [restaurant, review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, class: "form-select" %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/new.html.erb
<%= render template: 'restaurants/show' %>